// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tree.proto

#include "tree.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr TreeNodeProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : children_{},
        text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TreeNodeProto::TreeNodeProto(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TreeNodeProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TreeNodeProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TreeNodeProtoDefaultTypeInternal() {}
  union {
    TreeNodeProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TreeNodeProtoDefaultTypeInternal _TreeNodeProto_default_instance_;
static ::_pb::Metadata file_level_metadata_tree_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_tree_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_tree_2eproto = nullptr;
const ::uint32_t TableStruct_tree_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::TreeNodeProto, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::TreeNodeProto, _impl_.text_),
    PROTOBUF_FIELD_OFFSET(::TreeNodeProto, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::TreeNodeProto, _impl_.children_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::TreeNodeProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_TreeNodeProto_default_instance_._instance,
};
const char descriptor_table_protodef_tree_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\ntree.proto\"K\n\rTreeNodeProto\022\014\n\004text\030\001 "
    "\001(\t\022\n\n\002id\030\002 \001(\005\022 \n\010children\030\003 \003(\0132\016.Tree"
    "NodeProtob\006proto3"
};
static ::absl::once_flag descriptor_table_tree_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_tree_2eproto = {
    false,
    false,
    97,
    descriptor_table_protodef_tree_2eproto,
    "tree.proto",
    &descriptor_table_tree_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_tree_2eproto::offsets,
    file_level_metadata_tree_2eproto,
    file_level_enum_descriptors_tree_2eproto,
    file_level_service_descriptors_tree_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_tree_2eproto_getter() {
  return &descriptor_table_tree_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_tree_2eproto(&descriptor_table_tree_2eproto);
// ===================================================================

class TreeNodeProto::_Internal {
 public:
};

TreeNodeProto::TreeNodeProto(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TreeNodeProto)
}
inline PROTOBUF_NDEBUG_INLINE TreeNodeProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : children_{visibility, arena, from.children_},
        text_(arena, from.text_),
        _cached_size_{0} {}

TreeNodeProto::TreeNodeProto(
    ::google::protobuf::Arena* arena,
    const TreeNodeProto& from)
    : ::google::protobuf::Message(arena) {
  TreeNodeProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:TreeNodeProto)
}
inline PROTOBUF_NDEBUG_INLINE TreeNodeProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : children_{visibility, arena},
        text_(arena),
        _cached_size_{0} {}

inline void TreeNodeProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
TreeNodeProto::~TreeNodeProto() {
  // @@protoc_insertion_point(destructor:TreeNodeProto)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void TreeNodeProto::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.text_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void TreeNodeProto::Clear() {
// @@protoc_insertion_point(message_clear_start:TreeNodeProto)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.children_.Clear();
  _impl_.text_.ClearToEmpty();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* TreeNodeProto::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 26, 2> TreeNodeProto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_TreeNodeProto_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string text = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TreeNodeProto, _impl_.text_)}},
    // int32 id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TreeNodeProto, _impl_.id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TreeNodeProto, _impl_.id_)}},
    // repeated .TreeNodeProto children = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(TreeNodeProto, _impl_.children_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string text = 1;
    {PROTOBUF_FIELD_OFFSET(TreeNodeProto, _impl_.text_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 id = 2;
    {PROTOBUF_FIELD_OFFSET(TreeNodeProto, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .TreeNodeProto children = 3;
    {PROTOBUF_FIELD_OFFSET(TreeNodeProto, _impl_.children_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::TreeNodeProto>()},
  }}, {{
    "\15\4\0\0\0\0\0\0"
    "TreeNodeProto"
    "text"
  }},
};

::uint8_t* TreeNodeProto::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TreeNodeProto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string text = 1;
  if (!this->_internal_text().empty()) {
    const std::string& _s = this->_internal_text();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "TreeNodeProto.text");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 id = 2;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_id(), target);
  }

  // repeated .TreeNodeProto children = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_children_size()); i < n; i++) {
    const auto& repfield = this->_internal_children().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TreeNodeProto)
  return target;
}

::size_t TreeNodeProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TreeNodeProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .TreeNodeProto children = 3;
  total_size += 1UL * this->_internal_children_size();
  for (const auto& msg : this->_internal_children()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string text = 1;
  if (!this->_internal_text().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_text());
  }

  // int32 id = 2;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData TreeNodeProto::_class_data_ = {
    TreeNodeProto::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* TreeNodeProto::GetClassData() const {
  return &_class_data_;
}

void TreeNodeProto::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<TreeNodeProto*>(&to_msg);
  auto& from = static_cast<const TreeNodeProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TreeNodeProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_children()->MergeFrom(
      from._internal_children());
  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TreeNodeProto::CopyFrom(const TreeNodeProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TreeNodeProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool TreeNodeProto::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* TreeNodeProto::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void TreeNodeProto::InternalSwap(TreeNodeProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.children_.InternalSwap(&other->_impl_.children_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, &other->_impl_.text_, arena);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata TreeNodeProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tree_2eproto_getter, &descriptor_table_tree_2eproto_once,
      file_level_metadata_tree_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
